[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  NETLIFY_SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "true"
